import { ListingDetail, ListingSummary, LeadRecord } from "@/lib/marketplace-types";

const baseListings: ListingDetail[] = [
  {
    id: "1",
    title: "Toyota Corolla 2019",
    description: "Tam yoxlanılmış, sürücü tərəfindən qorunan, ilk sahibi tərəfindən idarə edilən avtomobil.",
    priceAzn: 19800,
    city: "Bakı",
    year: 2019,
    mileageKm: 72000,
    fuelType: "Benzin",
    transmission: "Avtomat",
    make: "Toyota",
    model: "Corolla",
    vin: "JTDBR32E720056789",
    status: "active",
    sellerType: "private",
    trustScore: 92,
    vinVerified: true,
    sellerVerified: true,
    mediaComplete: true,
    priceInsight: "below_market",
    mileageFlagSeverity: undefined,
    mileageFlagMessage: undefined,
    serviceHistorySummary: "4 rəsmi servis qeydi",
    riskSummary: "Aşağı risk",
    lastVerifiedAt: "2026-03-01T10:00:00Z",
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-03-01T10:00:00Z",
    bodyType: "Sedan",
    driveType: "Ön təkər",
    color: "Ağ",
    condition: "Qəzasız",
    serviceRecords: [
      {
        id: "svc-1",
        sourceType: "service_partner",
        serviceDate: "2025-11-03T10:00:00Z",
        mileageKm: 68000,
        summary: "Mühərrik yağı və filter dəyişikliyi"
      }
    ],
    mediaUrls: [],
    relatedIds: ["2", "3", "9"]
  },
  {
    id: "2",
    title: "Hyundai Elantra 2020",
    description: "Mükəmməl texniki vəziyyətdə, tam servis tarixçəsi mövcuddur.",
    priceAzn: 22400,
    city: "Bakı",
    year: 2020,
    mileageKm: 55000,
    fuelType: "Benzin",
    transmission: "Avtomat",
    make: "Hyundai",
    model: "Elantra",
    vin: "KMHD841DBLU123456",
    status: "active",
    sellerType: "dealer",
    dealerProfileId: "dealer-1",
    bodyType: "Sedan",
    driveType: "Ön təkər",
    color: "Bəyaz",
    condition: "Qəzasız",
    trustScore: 87,
    vinVerified: true,
    sellerVerified: true,
    mediaComplete: true,
    priceInsight: "market_rate",
    serviceHistorySummary: "3 servis qeydi",
    riskSummary: "Aşağı risk",
    lastVerifiedAt: "2026-03-01T10:00:00Z",
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-03-01T10:00:00Z",
    serviceRecords: [],
    mediaUrls: [],
    relatedIds: ["1", "6", "9"]
  },
  {
    id: "3",
    title: "Kia Sportage 2018",
    description: "Yaxşı vəziyyətdə SUV. Yürüşdə kiçik uyğunsuzluq müşahidə edilib.",
    priceAzn: 28900,
    city: "Sumqayıt",
    year: 2018,
    mileageKm: 98000,
    fuelType: "Benzin",
    transmission: "Avtomat",
    make: "Kia",
    model: "Sportage",
    vin: "KNDPB3A29J7543210",
    status: "active",
    sellerType: "private",
    trustScore: 71,
    vinVerified: true,
    sellerVerified: false,
    mediaComplete: true,
    mileageFlagSeverity: "warning",
    mileageFlagMessage: "Tarixi yürüş ilə elan arasında fərq var.",
    bodyType: "SUV",
    driveType: "Tam ötürmə (4x4)",
    color: "Gümüşü",
    condition: "Qəzasız",
    priceInsight: "market_rate",
    serviceHistorySummary: "2 servis qeydi",
    riskSummary: "Orta risk",
    lastVerifiedAt: "2026-03-01T10:00:00Z",
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-03-01T10:00:00Z",
    serviceRecords: [],
    mediaUrls: [],
    relatedIds: ["6", "8"]
  },
  {
    id: "4",
    title: "Mercedes-Benz C 200 2017",
    description: "Premium sinif sedan. Media protokolu tamamlanmayıb, əlavə yoxlama tövsiyə olunur.",
    priceAzn: 34500,
    city: "Bakı",
    year: 2017,
    mileageKm: 120000,
    fuelType: "Benzin",
    transmission: "Avtomat",
    make: "Mercedes-Benz",
    model: "C 200",
    vin: "WDD2050421R678901",
    status: "active",
    sellerType: "dealer",
    dealerProfileId: "dealer-1",
    bodyType: "Sedan",
    driveType: "Arxa təkər",
    color: "Qara",
    condition: "Rənglənmiş",
    trustScore: 68,
    vinVerified: true,
    sellerVerified: true,
    mediaComplete: false,
    priceInsight: "above_market",
    serviceHistorySummary: "1 servis qeydi",
    riskSummary: "Orta risk",
    lastVerifiedAt: "2026-03-01T10:00:00Z",
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-03-01T10:00:00Z",
    serviceRecords: [],
    mediaUrls: [],
    relatedIds: ["7", "5"]
  },
  {
    id: "5",
    title: "Volkswagen Passat 2021",
    description: "Sənədsiz, yeni kimi. Avropa versiyası, tam paket.",
    priceAzn: 31200,
    city: "Bakı",
    year: 2021,
    mileageKm: 38000,
    fuelType: "Dizel",
    transmission: "Avtomat",
    make: "Volkswagen",
    model: "Passat",
    vin: "WVWZZZ3CZME765432",
    status: "active",
    sellerType: "dealer",
    dealerProfileId: "dealer-1",
    bodyType: "Sedan",
    driveType: "Ön təkər",
    color: "Ağ",
    condition: "Qəzasız",
    trustScore: 95,
    vinVerified: true,
    sellerVerified: true,
    mediaComplete: true,
    priceInsight: "below_market",
    serviceHistorySummary: "Tam servis tarixçəsi",
    riskSummary: "Aşağı risk",
    lastVerifiedAt: "2026-03-01T10:00:00Z",
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-03-01T10:00:00Z",
    serviceRecords: [],
    mediaUrls: [],
    relatedIds: ["9", "2"]
  },
  {
    id: "6",
    title: "Nissan Qashqai 2019",
    description: "Ailə avtomobili, qəzasız, tam servis qeydləri mövcuddur.",
    priceAzn: 26700,
    city: "Gəncə",
    year: 2019,
    mileageKm: 84000,
    fuelType: "Benzin",
    transmission: "Avtomat",
    make: "Nissan",
    model: "Qashqai",
    vin: "SJNFBAJ11U1234567",
    status: "active",
    sellerType: "private",
    bodyType: "Crossover",
    driveType: "Ön təkər",
    color: "Ağ",
    condition: "Qəzasız",
    trustScore: 79,
    vinVerified: true,
    sellerVerified: true,
    mediaComplete: true,
    priceInsight: "market_rate",
    serviceHistorySummary: "3 servis qeydi",
    riskSummary: "Aşağı risk",
    lastVerifiedAt: "2026-03-01T10:00:00Z",
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-03-01T10:00:00Z",
    serviceRecords: [],
    mediaUrls: [],
    relatedIds: ["3", "8"]
  },
  {
    id: "7",
    title: "BMW 3 Series 2018",
    description: "Dinamik sürüş, yaxşı baxımlı mühərrik, premium salon.",
    priceAzn: 41000,
    city: "Bakı",
    year: 2018,
    mileageKm: 110000,
    fuelType: "Benzin",
    transmission: "Avtomat",
    make: "BMW",
    model: "3 Series",
    vin: "WBA8E1G54JNU45678",
    status: "active",
    sellerType: "dealer",
    dealerProfileId: "dealer-1",
    bodyType: "Sedan",
    driveType: "Arxa təkər",
    color: "Qara",
    condition: "Qəzasız",
    trustScore: 74,
    vinVerified: true,
    sellerVerified: true,
    mediaComplete: true,
    priceInsight: "market_rate",
    serviceHistorySummary: "2 servis qeydi",
    riskSummary: "Orta risk",
    lastVerifiedAt: "2026-03-01T10:00:00Z",
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-03-01T10:00:00Z",
    serviceRecords: [],
    mediaUrls: [],
    relatedIds: ["4", "5"]
  },
  {
    id: "8",
    title: "Honda CR-V 2020",
    description: "Ailə üçün ideal, geniş salon, qəzasız tarixçə.",
    priceAzn: 35800,
    city: "Bakı",
    year: 2020,
    mileageKm: 48000,
    fuelType: "Benzin",
    transmission: "Avtomat",
    make: "Honda",
    model: "CR-V",
    vin: "2HKRW2H83LH123456",
    status: "active",
    sellerType: "private",
    bodyType: "SUV",
    driveType: "Ön təkər",
    color: "Ağ",
    condition: "Qəzasız",
    trustScore: 89,
    vinVerified: true,
    sellerVerified: true,
    mediaComplete: true,
    priceInsight: "below_market",
    serviceHistorySummary: "2 servis qeydi",
    riskSummary: "Aşağı risk",
    lastVerifiedAt: "2026-03-01T10:00:00Z",
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-03-01T10:00:00Z",
    serviceRecords: [],
    mediaUrls: [],
    relatedIds: ["6", "3"]
  },
  {
    id: "9",
    title: "Skoda Octavia 2019",
    description: "Sərfəli dizel sedan, servis tarixçəsi mövcuddur.",
    priceAzn: 24300,
    city: "Lənkəran",
    year: 2019,
    mileageKm: 76000,
    fuelType: "Dizel",
    transmission: "Mexanik",
    make: "Skoda",
    model: "Octavia",
    vin: "TMBJG7NE7K0145678",
    status: "active",
    sellerType: "private",
    bodyType: "Sedan",
    driveType: "Ön təkər",
    color: "Qara",
    condition: "Qəzasız",
    trustScore: 82,
    vinVerified: true,
    sellerVerified: false,
    mediaComplete: true,
    priceInsight: "below_market",
    serviceHistorySummary: "3 servis qeydi",
    riskSummary: "Aşağı risk",
    lastVerifiedAt: "2026-03-01T10:00:00Z",
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-03-01T10:00:00Z",
    serviceRecords: [],
    mediaUrls: [],
    relatedIds: ["1", "2", "5"]
  }
];

export const demoListingsDetailed = baseListings;
export const demoListings = baseListings.map<ListingSummary>((entry) => ({ ...entry }));

export const demoLeads: LeadRecord[] = [
  {
    id: "lead-1",
    listingId: "2",
    dealerProfileId: "dealer-1",
    customerName: "Rashad M.",
    customerPhone: "+994501112233",
    note: "Bu həftə baxmaq istəyir",
    stage: "new",
    source: "listing_detail",
    responseTimeMinutes: 5,
    createdAt: "2026-03-01T11:00:00Z",
    updatedAt: "2026-03-01T11:00:00Z"
  },
  {
    id: "lead-2",
    listingId: "4",
    dealerProfileId: "dealer-1",
    customerName: "Leman A.",
    customerPhone: "+994551112233",
    note: "Qiymət danışmaq istəyir",
    stage: "contacted",
    source: "listing_detail",
    responseTimeMinutes: 18,
    createdAt: "2026-03-01T09:00:00Z",
    updatedAt: "2026-03-01T09:30:00Z"
  }
];

export const demoSavedSearches = [
  { id: "search-1", name: "Bakı sedan 20-30k", queryParams: { city: "Bakı", minPrice: 20000, maxPrice: 30000 } }
];
