export interface VehicleListingTitleInput {
  make: string;
  model: string;
  year: number;
  fuelType: string;
  mileageKm: number;
  color?: string | null;
}

function normalizeToken(value: string): string {
  return value.trim().replace(/\s+/g, " ");
}

function formatMileageForTitle(mileageKm: number): string {
  const safe = Number.isFinite(mileageKm) ? Math.max(0, Math.round(mileageKm)) : 0;
  return `${safe.toLocaleString("az-AZ")} KM`;
}

/** Canonical vehicle listing title used across cards, detail pages, and SEO. */
export function buildVehicleListingTitle(input: VehicleListingTitleInput): string {
  const make = normalizeToken(input.make).toUpperCase();
  const model = normalizeToken(input.model).toUpperCase();
  const fuel = normalizeToken(input.fuelType).toUpperCase();
  const color = input.color ? normalizeToken(input.color).toUpperCase() : "";
  const segments = [
    `${make} ${model} ${input.year}`.trim(),
    fuel,
    formatMileageForTitle(input.mileageKm)
  ];
  if (color) segments.push(color);
  return segments.join(" — ");
}

/** Detect titles generated by the canonical builder (or legacy close variants). */
export function isAutoGeneratedVehicleTitle(
  title: string,
  input: VehicleListingTitleInput
): boolean {
  const canonical = buildVehicleListingTitle(input);
  const normalizedTitle = normalizeToken(title).toUpperCase();
  const normalizedCanonical = normalizeToken(canonical).toUpperCase();
  if (normalizedTitle === normalizedCanonical) return true;

  const mileagePattern = /\b\d[\d\s.,]*\s*KM\b/i;
  const hasMakeModelYear =
    normalizedTitle.includes(normalizeToken(input.make).toUpperCase()) &&
    normalizedTitle.includes(normalizeToken(input.model).toUpperCase()) &&
    normalizedTitle.includes(String(input.year));

  return hasMakeModelYear && mileagePattern.test(title);
}

export function resolveVehicleListingTitle(
  currentTitle: string | undefined,
  input: VehicleListingTitleInput,
  options?: { forceCanonical?: boolean }
): string {
  const canonical = buildVehicleListingTitle(input);
  if (options?.forceCanonical) return canonical;
  if (!currentTitle?.trim()) return canonical;
  if (isAutoGeneratedVehicleTitle(currentTitle, input)) return canonical;
  return currentTitle.trim();
}

/** Short subtitle for sticky CTA — never reuses stale title mileage tokens. */
export function buildVehicleListingSubtitle(input: {
  year: number;
  mileageKm: number;
  fuelType: string;
  city: string;
  color?: string | null;
}): string {
  const parts = [
    String(input.year),
    formatMileageForTitle(input.mileageKm),
    normalizeToken(input.fuelType)
  ];
  if (input.color?.trim()) parts.push(normalizeToken(input.color));
  parts.push(normalizeToken(input.city));
  return parts.join(" • ");
}

export function formatEngineVolumeLiters(engineVolumeCc?: number | null): string | null {
  if (engineVolumeCc === undefined || engineVolumeCc === null || !Number.isFinite(engineVolumeCc) || engineVolumeCc <= 0) {
    return null;
  }
  const liters = Math.round(engineVolumeCc / 100) / 10;
  return Number.isInteger(liters) ? `${liters} L` : `${liters.toFixed(1)} L`;
}
